# Generated by Django 4.1.2 on 2022-11-10 23:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("skin_classifier", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="report", old_name="Urgency", new_name="urgency",
        ),
    ]
